language: ruby
rvm:
  - rvm 2.2.5
  - rvm 2.3.0

before_install:
  - sudo apt-get install postgresql-server-dev-9.5 libpq-dev

before_script:
  - psql -c 'create database sms_two_fa_sinatra_test;' -U postgres

env:
  global:
    - TWILIO_ACCOUNT_SID=TWILIO-ACCOUNT-SID
    - TWILIO_AUTH_TOKEN=TWILIO-AUTH-TOKEN
    - TWILIO_PHONE_NUMBER=TWILIO-PHONE-NUMBER
