name: Build and test

on:
  push:
    branches:
      - master
      - test
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        ruby: [ 2.6.4 ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Install OS dependencies
        run: |
          sudo apt install -y postgresql-12 postgresql-server-dev-12 libpq-dev
      - name: Install gems
        run: |
          gem install bundler:1.17.2
          bundle install --jobs=3 --retry=3 --deployment
      - name: Run tests
        run: |
          cp .env.example .env
          bundle exec rspec
